apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: microservices-with-docker-k-s
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: titusdishon/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: titusdishon/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: titusdishon/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
           - src: "*.js"
             dest: .
    - image: titusdishon/moderations
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: titusdishon/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
           - src: "*.js"
             dest: .
    - image: titusdishon/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
           - src: "*.js"
             dest: .

deploy:
  kubectl:
    manifests:
      - infra/k8s/*
