apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: microservices-with-docker-k-s
build:
  local:
    push: false
  artifacts:
    - image: titusdishon/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/*.js"
    - image: titusdishon/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: titusdishon/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: titusdishon/moderations
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: titusdishon/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
    - image: titusdishon/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
deploy:
  kubectl:
    manifests:
      - infra/k8s/client-depl.yaml
      - infra/k8s/comments-depl.yaml
      - infra/k8s/event-bus-dep.yaml
      - infra/k8s/ingress-srv.yaml
      - infra/k8s/moderations-depl.yaml
      - infra/k8s/posts-dep.yaml
      - infra/k8s/query-depl.yaml
